name: Go CI Workflow

# Trigger the workflow when code is pushed to the `main` branch or when a pull request is created for `main`
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run in the workflow
jobs:
  # This job will run on an Ubuntu virtual environment
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'  # Specify Go version

      # Step 3: Install dependencies (if using Go modules)
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run tests
      - name: Run tests
        run: go test ./...
